### ISSUE TITLE
token 过期时间会自动刷新吗？

### ISSUE THREAD

**Issue by LiuQiV5** [HowieYuan/Shiro-SpringBoot#5]
您好，我看了下您的代码token过期时间是24小时，请问如果我在这个过期时间段内访问了你的接口，token过期时间都不会和session过期时间一样往后顺延吗?只要与token创建时间相隔24小时就肯定过期吗?

**Comment by HowieYuan** [comment]
token 本身的过期时间的固定的，你的需求可以参考refresh token的设计方式
